"""Add role specific fields for student and vendor

Revision ID: 0e25d93cd999
Revises: c145f775fe29
Create Date: 2026-01-26 10:31:30.851956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e25d93cd999'
down_revision = 'c145f775fe29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vendor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('business_type')
        batch_op.drop_column('business_name')
        batch_op.drop_column('vendor_name')
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
