"""Phase 4 Categories

Revision ID: 3c080c8bca7b
Revises: 185eb8089d31
Create Date: 2026-01-21 16:24:18.252625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c080c8bca7b'
down_revision = '185eb8089d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
