"""Add merchant_id and is_static fields

Revision ID: 6812ba34e0b9
Revises: 3c080c8bca7b
Create Date: 2026-01-24 15:19:45.705972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6812ba34e0b9'
down_revision = '3c080c8bca7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_static', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_user_merchant_id', ['merchant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_merchant_id', type_='unique')
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.drop_column('is_static')

    # ### end Alembic commands ###
