"""add numeric_code to qrcode

Revision ID: d10638947c6b
Revises: e3cfb253db04
Create Date: 2026-02-08 13:38:11.639250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10638947c6b'
down_revision = 'e3cfb253db04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeric_code', sa.String(length=6), nullable=True))
        batch_op.create_unique_constraint('uq_qr_code_numeric_code', ['numeric_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.drop_constraint('uq_qr_code_numeric_code', type_='unique')
        batch_op.drop_column('numeric_code')

    # ### end Alembic commands ###
