"""add status to scheduled topup

Revision ID: e3cfb253db04
Revises: c85212c56c61
Create Date: 2026-02-07 12:33:36.376692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cfb253db04'
down_revision = 'c85212c56c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_topup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_scheduled_topup_reviewed_by_user', 'user', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_topup', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scheduled_topup_reviewed_by_user', type_='foreignkey')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
