"""Add vendor approval field

Revision ID: e5021fa84c64
Revises: 0e25d93cd999
Create Date: 2026-01-26 10:41:05.541325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5021fa84c64'
down_revision = '0e25d93cd999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved_vendor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approved_vendor')

    # ### end Alembic commands ###
